# Generated by Django 2.0.6 on 2018-07-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cinemalm',
            table='cinema_lm',
        ),
        migrations.AlterModelTable(
            name='cinemamt',
            table='cinema_mt',
        ),
        migrations.AlterModelTable(
            name='cinematb',
            table='cinema_tb',
        ),
    ]
