# Generated by Django 2.0.6 on 2018-07-10 14:20

import base.models.channel
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityLM',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('g', models.CharField(max_length=2, verbose_name='分组')),
                ('name', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time', verbose_name='update time')),
            ],
            options={
                'managed': False,
                'db_table': 'city_lm',
            },
            bases=(models.Model, base.models.channel.ChannelLM),
        ),
        migrations.CreateModel(
            name='CityMT',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('g', models.CharField(max_length=2, verbose_name='分组')),
                ('name', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time', verbose_name='update time')),
            ],
            options={
                'managed': False,
                'db_table': 'city_mt',
            },
            bases=(models.Model, base.models.channel.ChannelMT),
        ),
        migrations.CreateModel(
            name='CityTB',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('g', models.CharField(max_length=2, verbose_name='分组')),
                ('name', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time', verbose_name='update time')),
            ],
            options={
                'managed': False,
                'db_table': 'city_tb',
            },
            bases=(models.Model, base.models.channel.ChannelTB),
        ),
    ]
